### PR TITLE
Windows support building from source

### PR DESCRIPTION
**Pull request by kstuart**
Decided to clean up the build script to make linking simpler which cascaded so quite a lot of changes to CMake script, tested on Windows 10 and Ubuntu with all tests passing (and faster compiles).

Webassembly builds but tests don't pass, not sure if currently supported as travis doesn't appear to be running the tests, though the README indicates Webassembly platform support, but maybe not on master branch?

Windows debug builds do bounds checking so tests fail due to issue first identified by @som-dev in PR #116, however merging that PR would conflict with this one as the C99 VLAs have been replaced for MSVC compatibility, this PR includes PR #116 overflow correction.

Setting the thread count for make in setup.py isn't portable so I had to remove it, it could be set in a MAKEFLAGS environment variable.

Linked to #38

### CODE REVIEW

**Comment by jleni** [comment]
Thanks @kstuart ! 
I will have a look as soon as I get home (in a couple of days).

**Comment by jleni** [comment]
by the way, this is unlikely to be working in Windows.

https://github.com/theQRL/qrllib/blob/853c4badd7fea8bfdfa576a8b5de1e3fb34874c4/src/qrl/misc.cpp#L125

Actually, it is possible that we dont have a unit test that flags the issue.

**Comment by som-dev** [comment]
I would advocate compiling with windows clang which does support VLAs.  All of the array declarations could then be restored to their original form without the alloca() calls.  I suspect most windows users would use pre-compiled applications so the extra requirement for clang should not be a large burden.

**Comment by jleni** [comment]
Yes, VLA is something I dont like. Actually, this is all coming from the original reference code for xmss.
We plan to align with the most recent reference code, drop alt-xmss and maybe send a PR upstream that avoids VLAs. The main issues I see with Windows support and why I have been avoiding it a bit are:
- random number generation. It is easy to fix with some Win32 API calls
- building pypi packages. It requires a lot of dependencies and not every Windows use use to these things. At some point we should start supporting python wheels (at least for Windows)

In the medium term, we need to move to installers and leave the pypi realm.

**Comment by jleni** [comment]
Now that you guys are looking at Windows support, it is probably a good idea to setup Appveyor, etc.
@kstuart are you already in Discord? do you have access to the contributors channel? Ping me and I can give you access there. I am travelling at the moment, but it will be easier to reach me next week.

**Comment by kstuart** [comment]
kick travis to retry build.

**Pull request merged**
